## This script will take in the dataframes produced by
## get_counts.R and conduct all the analyses and 
## generate all the plots shown in the paper.

## NOTE: The plots in the paper were generated by running
## this script on a 2017 iMac with 4096x2304 resolution.
## Running this on a different computer will yield the same
## numerical results, but the plots will probably look
## different if the resolution is different (e.g., axis
## labels might look smaller than they do in the paper).
## Note also that, for the paper, I created legends in
## LaTeX using the tikz package. This script will produce
## plots with no legends.

#install.packages("tidyverse")
#install.packages("forecast")
#install.packages("ggtext")
#install.packages("zoo")
#install.packages("emojifont")
#install.packages("xtable")
#install.packages("urca")

library(tidyverse)
library(forecast)
library(ggtext)
library(zoo)
library(emojifont)
library(xtable)
library(urca)

# Colors

my_blue <- "#077b8a"
my_red <- "#d72631"
my_light_blue <- "#a2d5c6"
blue_ribbon <- "#6699CC"
blue_obs <- "#96b8da"
my_green <- "#389150"
my_light_gray <- "#a0a6ac"

intentBlue <- "#4D83B3"
undeterOrange <- "#F18805"
unintentRed <- "#BC2C1A"

my_gray <- "#7a8086"

#### MAIN ANALYSIS ####

# Reading in data
tg <- readRDS(here("data", "tg_self_harm.rds"))

# Preparing ts objects
tg_all <- create_ts(tg)

# Saving all list items to global environment
list2env(tg_all, globalenv())

#Obtaining split model order
split_mod <- give_me_order(ts_train_fsd)

split_order_fsd <- split_mod$order
split_seasonal_fsd <- split_mod$seasonal

# Adjusting ARIMA order for non-differenced
# data. This does not change the results; it
# just makes it easier to present plots with 
# raw (rather than differenced) data

split_order <- split_order_fsd
split_order[2] <- 1

split_seasonal <- split_seasonal_fsd
split_seasonal[2] <- 1

# Selecting model using full pre-treatment ts.
# Here I'm just letting the ARIMA do the differencing
# from the outset so I don't have to add in the d / D
# parameters later (as I do above)

full_mod <- give_me_order(pre_ts)

full_order <- full_mod$order
full_seasonal <- full_mod$seasonal

full_mod <- auto.arima(pre_ts)
full_order <- as.numeric(arimaorder(full_mod)[1:3])
full_seasonal <- as.numeric(arimaorder(full_mod)[4:6])

### FIGURE 3: MAIN TREATMENT EFFECT ESTIMATE WITH CONFORMAL
### PREDICTION INTERVALS, PLOTTED

tg_PI <- get_arima_PI(ts_full_conf_1,
                      T1 = 1,
                      T0 = length(pre_ts),
                      alpha = 0.05,
                      pi_grid = 8000:10000, 
                      block_size = 1,
                      order = full_order,
                      seasonal = full_seasonal,
                      include.mean = F)

tg_upper <- tg_PI$ub
tg_lower <- tg_PI$lb

tg_dfs <- get_plot_dfs(ts_full_conf_1, full_mod, tg_upper, tg_lower)

get_control_plot(pre_df = tg_dfs$pre_df,
                 post_df = tg_dfs$post_df,
                 name = "tg",
                 y_min = 6500,
                 y_max = 10500)

### FIGURE 4: TREATMENT EFFECT ESTIMATES FOR OTHER GROUPS

## TEEN BOYS

tb <- readRDS(here("data", "tb_selfh_all_full.rds"))
tb_ts <- create_ts(tb)
tb_ts_pre <- tb_ts$pre_ts
tb_ts_post <- tb_ts$ts_full_conf_1

# The auto.arima() function doesn't select both forms of differencing for 
# teen boys, so here I force it to be consistent with the rest of the 
# analyses by setting d = 1, D = 1. In the appendix section of this script, 
# I re-run the analysis without forced differencing. The results change 
# very little.

ords <- give_me_order(tb_ts_pre, d = 1, D = 1)

tb_mod <- Arima(tb_ts_pre, order = ords$order, seasonal = ords$seasonal, include.mean = F)

tb_PI <- get_arima_PI(tb_ts_post, 
                      T1 = 1, 
                      T0 = length(tb_ts_pre),
                      alpha = 0.05, 
                      pi_grid = 2500:3800, 
                      block_size = 1,
                      order = ords$order, 
                      seasonal = ords$seasonal, 
                      include.mean = F)

tb_upper <- tb_PI$ub
tb_lower <- tb_PI$lb

tb_dfs <- get_plot_dfs(tb_ts_post, tb_mod, tb_upper, tb_lower)

get_control_plot(pre_df = tb_dfs$pre_df,
                 post_df = tb_dfs$post_df,
                 name = "tb",
                 y_min = 1000,
                 y_max = 5000)

## MEN 40-65

m40 <- readRDS(here("data", "m40_selfh_all_full.rds"))
m40_ts <- create_ts(m40)
m40_ts_pre <- m40_ts$pre_ts
m40_ts_post <- m40_ts$ts_full_conf_1
ords <- give_me_order(m40_ts_pre)

m40_mod <- Arima(m40_ts_pre, order = ords$order, seasonal = ords$seasonal, include.mean = F)

m40_PI <- get_arima_PI_CSS(m40_ts_post, 
                           T1 = 1, 
                           T0 = length(m40_ts_pre),
                           alpha = 0.05, 
                           pi_grid = 3500:5000, 
                           block_size = 1,
                           order = ords$order, 
                           seasonal = ords$seasonal, 
                           include.mean = F)

m40_upper <- m40_PI$ub
m40_lower <- m40_PI$lb

m40_dfs <- get_plot_dfs(m40_ts_post, m40_mod, m40_upper, m40_lower)

get_control_plot(pre_df = m40_dfs$pre_df,
                 post_df = m40_dfs$post_df,
                 name = "m40",
                 y_min = 2000,
                 y_max = 6000)

## WOMEN 40-65

w40 <- readRDS(here("data", "w40_selfh_all_full.rds"))
w40_ts <- create_ts(w40)
w40_ts_pre <- w40_ts$pre_ts
w40_ts_post <- w40_ts$ts_full_conf_1
ords <- give_me_order(w40_ts_pre)

w40_mod <- Arima(w40_ts_pre, order = ords$order, seasonal = ords$seasonal, include.mean = F)

w40_PI <- get_arima_PI(w40_ts_post, 
                       T1 = 1, 
                       T0 = length(w40_ts_pre),
                       alpha = 0.05, 
                       pi_grid = 4500:6000, 
                       block_size = 1,
                       order = ords$order, 
                       seasonal = ords$seasonal, 
                       include.mean = F)

w40_upper <- w40_PI$ub
w40_lower <- w40_PI$lb

w40_dfs <- get_plot_dfs(w40_ts_post, w40_mod, w40_upper, w40_lower)

get_control_plot(pre_df = w40_dfs$pre_df,
                 post_df = w40_dfs$post_df,
                 name = "w40",
                 y_min = 3000,
                 y_max = 7000)

### FIGURE 5: FOUR-STEP-AHEAD FORECAST WITH BOOTSTRAPPED-RESIDUAL
### PREDICTION INTERVALS

post_df <- data.frame(matrix(NA, nrow = 5, ncol = 6))

colnames(post_df) <- c("date", "obs", "forecast", "upper", "lower", "treat")

msa_forecast <- forecast(full_mod, h = 4, level = 95, bootstrap = T)

# The df will contain one pre-forecast row for ggplot purposes.
post_df$date <- seq.Date(from = as.Date("2017-03-01"), to = as.Date("2017-07-01"), by = "1 month")
post_df$obs <- full_ts[135:139]
post_df$forecast <- c(fitted(full_mod)[135], as.numeric(msa_forecast$mean))
post_df$upper <- c(fitted(full_mod)[135], as.numeric(msa_forecast$upper))
post_df$lower <- c(fitted(full_mod)[135], as.numeric(msa_forecast$lower))

post_df$treat <- c(0,1,1,1,1)

pre_df <- data.frame(date = seq.Date(from = as.Date("2016-11-01"), to = as.Date("2017-03-01"), by = "1 month"),
                     obs = c(full_ts[131:134], NA),
                     fitted = fitted(full_mod)[131:135])

ggplot() + 
  geom_vline(aes(xintercept = as.Date("2017-02-15")), linetype = "dotted") +
  geom_vline(aes(xintercept = as.Date("2017-03-15")), linetype = "dotted") +
  geom_line(pre_df, mapping = aes(x = date, y = fitted), size = 0.7) +
  geom_point(pre_df, mapping = aes(x = date, y = obs), color = blue_obs, size = 8, alpha = .7, shape ="\u25cf") +
  geom_line(post_df, mapping = aes(x = date, y = forecast), linetype = "dashed", size = 0.7) +
  geom_ribbon(post_df, mapping = aes(x = date, ymin = lower, ymax = upper), fill = blue_ribbon, alpha = .2) +
  geom_point(post_df, mapping = aes(x = date, y = obs, color = factor(treat), shape = factor(treat), size = factor(treat)),
             alpha = .7) +
  scale_color_manual(values = c(blue_obs, my_green)) +
  scale_shape_manual(values = c("\u25cf", "\u25b2")) +
  scale_size_manual(values = c(8,10)) +
  theme_classic() +
  theme(legend.title = element_blank(),
        legend.position = "none",
        text = element_text(size = 20)) +
  scale_x_date(
    date_labels = "%b %Y",
    breaks = c(as.Date("2016-12-01"),
               as.Date("2017-03-01"),
               as.Date("2017-06-01"))) +
  scale_y_continuous(limits = c(6300, 12300),
                     breaks = c(7000, 9000, 11000)) +
  ylab("") +
  xlab("")

ggsave(here("plots", "tau_length.png"), width = 8, height = 6, units = "in")

### FIGURE 6: TEXT CUTTING PLOT

tg <- tg %>%
  mutate(treat = ifelse(date == as.Date("2017-04-01"), 1, 0),
         treat2 = ifelse(date == as.Date("2017-04-01"), 1,
                         ifelse(date == as.Date("2017-05-01"), 1, 0)),
         cut_prop_fd = cut_prop - lag(cut_prop),
         cut_prop_sfd = cut_prop_fd - lag(cut_prop_fd, n = 12),
         shcolor = ifelse(date < as.Date("2017-04-01"), 1,
                          ifelse(date < as.Date("2017-06-01"), 2, 3)))

tg_for_supp <- tg %>%
  mutate(mon = format(tg$date, "%b"),
         apr_may = ifelse(mon == "Apr", 1,
                          ifelse(mon == "May", 1, 0)))

tg_apr_may <- tg_for_supp[tg_for_supp$mon == "Apr" | tg_for_supp$mon == "May",]
tg_no_apr <- tg_for_supp[tg_for_supp$mon != "Apr" & tg_for_supp$mon != "May",]

ggplot() +
  #geom_point(mapping = aes(x = year, y = cut_prop, label = mon)) +
  geom_text(tg_no_apr, mapping = aes(x = year, y = cut_prop, label = mon), alpha = 0.5) +
  geom_text(tg_apr_may, mapping = aes(x = year, y = cut_prop, label = mon), color = "red", fontface = "bold") +
  theme_classic() +
  theme(text = element_text(size = 20),
        legend.position = "none") +
  scale_x_continuous(labels = as.character(2006:2017), breaks = 2006:2017) +
  ylab("") +
  xlab("")

ggsave(here("plots", "text_plot.png"), width = 8, height = 5, unit = "in")

### CUTTING PERCENTILE FIGURES REFERENCED IN TEXT

prop_lower <- quantile(tg$cut_prop, probs = .05)
prop_upper <- quantile(tg$cut_prop, probs = .95)

tg <- tg %>%
  group_by(year) %>%
  mutate(cut_prop_demeaned = cut_prop - mean(cut_prop)) %>%
  ungroup()

which(order(tg$cut_prop, decreasing = T) == 136)
which(order(tg$cut_prop, decreasing = T) == 137)

length(tg$cut_prop[tg$cut_prop <= tg$cut_prop[136]])/length(tg$cut_prop)*100
length(tg$cut_prop[tg$cut_prop <= tg$cut_prop[137]])/length(tg$cut_prop)*100

which(order(tg$cut_prop_demeaned, decreasing = T) == 136)
which(order(tg$cut_prop_demeaned, decreasing = T) == 137)

length(tg$cut_prop_demeaned[tg$cut_prop_demeaned <= tg$cut_prop_demeaned[136]])/length(tg$cut_prop_demeaned)*100
length(tg$cut_prop_demeaned[tg$cut_prop_demeaned <= tg$cut_prop_demeaned[137]])/length(tg$cut_prop_demeaned)*100

order(tg$cut_prop, decreasing = T)
order(tg$cut_prop_demeaned, decreasing = T)

tg_cut_pre <- tg$cut_prop[1:137]

which(order(tg_cut_pre, decreasing = T) == 136)
which(order(tg_cut_pre, decreasing = T) == 137)

length(tg_cut_pre[tg_cut_pre <= tg_cut_pre[136]])/length(tg_cut_pre)*100
length(tg_cut_pre[tg_cut_pre <= tg_cut_pre[137]])/length(tg_cut_pre)*100

### FIGURE 7: MULTI-STEP-AHEAD PLOTS FOR ALTERNATIVE
### FORECASTING CUTOFFS

multi_dfs <- get_multi_dfs(np = 6, start_date = as.Date("2016-10-01"), full_ts = full_ts)

inf_df <- multi_dfs[[2]]

mod1 <- multi_dfs[[1]][[1]]
mod2 <- multi_dfs[[1]][[2]]
mod3 <- multi_dfs[[1]][[3]]
mod4 <- multi_dfs[[1]][[4]]
mod5 <- multi_dfs[[1]][[5]]
mod6 <- multi_dfs[[1]][[6]]

make_multi_plots(start_date = as.Date("2016-09-01"), 6)

### FIGURE 8: INJURY VISITS BY TYPE AND INTENT

tg_cut_poison <- readRDS(here("data", "tg_cut_poison.rds"))

tg_cut_poison_17 <- tg_cut_poison %>%
  filter(date > as.Date("2016-12-01") & date < as.Date("2017-06-01"))

tg_cut_poison_16 <- tg_cut_poison %>%
  filter(date >= as.Date("2016-01-01") & date < as.Date("2016-06-01")) %>%
  mutate(date = as.Date(str_replace(as.character(date), "2016", "2017")))

ggplot() +
  geom_vline(mapping = aes(xintercept = as.Date("2017-02-15")), linetype = "dashed", size =.3) +
  geom_vline(mapping = aes(xintercept = as.Date("2017-03-15")), linetype = "dashed", size = .3) +
  geom_line(data = tg_cut_poison_16, mapping = aes(x = date, y=cut_poison, color = type), alpha = 0.6) +
  geom_point(data = tg_cut_poison_16, mapping = aes(x = date, y=cut_poison, shape = type, color = type), size = 3) +
  geom_text(data = tg_cut_poison_16, mapping = aes(x = date, y = cut_poison, 
                                                   label = ifelse(date == as.Date("2017-05-01"), year, ""), color = type),
            hjust = -.5, vjust = ifelse(tg_cut_poison_16$type == "undeter", -0.1, 0.45)) +
  geom_line(data = tg_cut_poison_17, mapping = aes(x = date, y=cut_poison, color = type), alpha = 0.6) +
  geom_point(data = tg_cut_poison_17, mapping = aes(x = date, y=cut_poison, shape = type, color = type), size = 3) +
  geom_text(data = tg_cut_poison_17, mapping = aes(x = date, y = cut_poison, 
                                                   label = ifelse(date == as.Date("2017-05-01"), year, ""), color = type),
            hjust = -.5, vjust = ifelse(tg_cut_poison_17$type == "undeter", 0.95, 0.45)) +
  scale_color_manual(values = c(intentBlue, undeterOrange, unintentRed)) +
  scale_shape_manual(values = c(15, 17, 19)) +
  theme_classic() +
  theme(text = element_text(size = 20),
        legend.position = "none") +
  scale_x_date(
    #date_labels = "%b %Y",
    #limits = c(as.Date("2016-01-01"), as.Date("2017-04-01")),
    expand = c(0,11)) +
  #ylim(-2900,2900) +
  ylab("") +
  xlab("")

ggsave(here("plots", "tg_cut_poison.png"), width = 8, height = 5, unit = "in")

ggplot() +
  geom_vline(mapping = aes(xintercept = as.Date("2017-02-15")), linetype = "dashed", size =.3) +
  geom_vline(mapping = aes(xintercept = as.Date("2017-03-15")), linetype = "dashed", size = .3) +
  geom_line(data = tg_cut_poison_16, mapping = aes(x = date, y=cutting, color = type), alpha = 0.6) +
  geom_point(data = tg_cut_poison_16, mapping = aes(x = date, y=cutting, shape = type, color = type), size = 3) +
  geom_text(data = tg_cut_poison_16, mapping = aes(x = date, y = cutting, 
                                                   label = ifelse(date == as.Date("2017-05-01"), year, ""), color = type),
            hjust = -.5, vjust = ifelse(tg_cut_poison_16$type == "undeter", 0.95, 0.45)) +
  geom_line(data = tg_cut_poison_17, mapping = aes(x = date, y=cutting, color = type), alpha = 0.6) +
  geom_point(data = tg_cut_poison_17, mapping = aes(x = date, y=cutting, shape = type, color = type), size = 3) +
  geom_text(data = tg_cut_poison_17, mapping = aes(x = date, y = cutting, 
                                                   label = ifelse(date == as.Date("2017-05-01"), year, ""), color = type),
            hjust = -.5, vjust = ifelse(tg_cut_poison_17$type == "undeter", -0.1, 0.45)) +
  scale_color_manual(values = c(intentBlue, undeterOrange, unintentRed)) +
  scale_shape_manual(values = c(15, 17, 19)) +
  theme_classic() +
  theme(text = element_text(size = 20),
        legend.position = "none") +
  scale_x_date(
    #date_labels = "%b %Y",
    #limits = c(as.Date("2016-01-01"), as.Date("2017-04-01")),
    expand = c(0,11)) +
  #ylim(-2900,2900) +
  ylab("") +
  xlab("")

ggsave(here("plots", "tg_cut.png"), width = 8, height = 5, unit = "in")

ggplot() +
  geom_vline(mapping = aes(xintercept = as.Date("2017-02-15")), linetype = "dashed", size =.3) +
  geom_vline(mapping = aes(xintercept = as.Date("2017-03-15")), linetype = "dashed", size = .3) +
  geom_line(data = tg_cut_poison_16, mapping = aes(x = date, y=poison, color = type), alpha = 0.6) +
  geom_point(data = tg_cut_poison_16, mapping = aes(x = date, y=poison, shape = type, color = type), size = 3) +
  geom_text(data = tg_cut_poison_16, mapping = aes(x = date, y = poison, 
                                                   label = ifelse(date == as.Date("2017-05-01"), year, ""), color = type),
            hjust = -.5, vjust = ifelse(tg_cut_poison_16$type == "undeter", -0.1, 
                                        ifelse(tg_cut_poison_16$type == "unintent", 0.95, 0.45))) +
  geom_line(data = tg_cut_poison_17, mapping = aes(x = date, y=poison, color = type), alpha = 0.6) +
  geom_point(data = tg_cut_poison_17, mapping = aes(x = date, y=poison, shape = type, color = type), size = 3) +
  geom_text(data = tg_cut_poison_17, mapping = aes(x = date, y = poison, 
                                                   label = ifelse(date == as.Date("2017-05-01"), year, ""), color = type),
            hjust = -.5, vjust = ifelse(tg_cut_poison_17$type == "undeter", 0.95,
                                        ifelse(tg_cut_poison_17$type == "unintent", -0.2, 0.45))) +
  scale_color_manual(values = c(intentBlue, undeterOrange, unintentRed)) +
  scale_shape_manual(values = c(15, 17, 19)) +
  theme_classic() +
  theme(text = element_text(size = 20),
        legend.position = "none") +
  scale_x_date(
    #date_labels = "%b %Y",
    #limits = c(as.Date("2016-01-01"), as.Date("2017-04-01")),
    expand = c(0,11)) +
  #ylim(-2900,2900) +
  ylab("") +
  xlab("")

ggsave(here("plots", "tg_poison.png"), width = 8, height = 5, unit = "in")

dat <- data.frame(type = as.factor(c(1,2,3)), x = c(1,2,3), y = c(1,2,3))

ggplot(dat) +
  geom_point(mapping = aes(x,y, color = type, shape = type), size = 3) +
  scale_color_manual(values = c(intentBlue, undeterOrange, unintentRed)) +
  scale_shape_manual(values = c(15, 17, 19)) +
  theme_classic() +
  theme(text = element_text(size = 20),
        legend.position = "none") +
  #ylim(-2900,2900) +
  ylab("") +
  xlab("")

ggsave(here("plots", "forlegend.png"), height = 5, width = 8, unit = "in")

### FIGURES 9--11 

## The code for reproducing these figures is in repeat_placebo.R because
## it takes a long time to run. I recommend running it overnight.

### FIGURE 12: ABSOLUTE RESIDUALS BY MONTH

complete_mod <- Arima(full_ts, order = full_order, seasonal = full_seasonal)

abs_res <- abs(as.numeric(complete_mod$residuals))[14:length(complete_mod$residuals)]

res <- as.numeric(complete_mod$residuals)[14:length(complete_mod$residuals)]

dates <- seq.Date(from = as.Date("2007-02-01"),
                  to = as.Date("2017-12-01"),
                  by = "1 month")

plot_month_df <- data.frame(abs_res, res, dates) %>%
  mutate(mon = format(dates, "%b"),
         year = format(dates, "%Y"),
         shcolor = ifelse(dates < as.Date("2017-04-01"), 1,
                          ifelse(dates < as.Date("2017-06-01"), 2, 3)))

plot_month_0916 <- plot_month_df %>%
  filter(year != "2017")

plot_month_17 <- plot_month_df %>%
  filter(year == "2017") %>%
  mutate(treat = ifelse(dates < as.Date("2017-04-01"), 0, 1))

ggplot() +
  geom_point(plot_month_0916, mapping = aes(x = mon, y = abs_res), shape = 16, size = 3.3, 
             color = my_light_gray, alpha = 0.6) +
  geom_text(plot_month_0916, mapping = aes(x = mon, y = abs_res, label = year), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 3, alpha = 0.6) +
  geom_point(plot_month_17, mapping = aes(x = mon, y = abs_res, shape = factor(treat), color = factor(treat), size = factor(treat))) +
  scale_shape_manual(values = c(16, 17)) +
  scale_color_manual(values = c(my_red, my_green)) +
  scale_size_manual(values = c(3.3,3)) +
  geom_text(plot_month_17, mapping = aes(x = mon, y = abs_res, label = year, color = factor(treat)), 
            hjust = -.5, vjust = 0.45, size = 3) +
  #scale_color_manual(values = c(my_red, my_green)) +
  theme_classic() +
  theme(legend.title = element_blank(),
        legend.position = "none",
        text = element_text(size = 20)) +
  scale_x_discrete(limits = c("Jan", "Feb", "Mar", "Apr", "May",
                              "Jun", "Jul", "Aug", "Sep", "Oct",
                              "Nov", "Dec"),
                   expand = c(0,1)) + 
  scale_y_continuous(limits = c(0,1500), expand = c(0,40)) +
  labs(x = "",
       y = "")

ggsave(here("plots", "month_res_plot.png"), width = 8, height = 5, unit = "in")

### FIGURE 13: RESIDUALS ACROSS TIME

dgray <- "#7e8082"
lgray <- "#b5b9bc"

ggplot() +
  geom_hline(yintercept = 0, linetype = "dotted") +
  geom_point(plot_month_df, mapping = aes(x = dates, y = res, shape = factor(shcolor), color = factor(shcolor)), size = 4) +
  scale_shape_manual(values = c(19, 17, 15)) +
  scale_color_manual(values = c(dgray, my_red, lgray)) +
  theme_classic() +
  theme(legend.title = element_blank(),
        legend.position = "none",
        text = element_text(size = 20)) +
  ylim(-1400, 1400) +
  labs(x = "",
       y = "")

ggsave(here("plots", "res_plot.png"), width = 8, height = 5, unit = "in")

### FIGURE 14: MODEL-FREE PLOT

start_dates <- seq.Date(from = as.Date("2011-09-01"), to = as.Date("2016-09-01"), by = "1 year")
end_dates <- seq.Date(from = as.Date("2012-06-01"), to = as.Date("2017-06-01"), by = "1 year")
for_names <- 12:17

#These are not the actual dates, just dates to make plotting in ggplot
#easier, since we're plotting a different line for each year
ggplot_dates <- seq.Date(from = as.Date("2016-10-01"), to = as.Date("2017-05-01"), by = "1 month")

for (i in 1:length(for_names)) {
  
  df_temp <- tg %>%
    filter(date > start_dates[i] & date < end_dates[i]) %>%
    select(self_h, self_h_fd, date) %>%
    mutate(date = ggplot_dates,
           year = paste0("20", for_names[i]))
  
  df_name <- paste0("df_", for_names[i])
  eval(call("<-", as.name(df_name), df_temp))
  
}

my_light_gray <- "#a0a6ac"
another_blue <- "#3080d0"

#using wide ylims to make room for labels in latex

ggplot() +
  geom_vline(df_17, mapping = aes(x = date, xintercept = as.Date("2017-02-15")), linetype = "dashed") +
  geom_vline(df_17, mapping = aes(x = date, xintercept = as.Date("2017-03-15")), linetype = "dashed") +
  geom_line(df_16, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_16, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_16, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-05-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_15, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_15, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_15, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-05-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_14, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_14, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_14, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-05-01"), year, "")), 
            hjust = -.5, vjust = 0.35, color = my_light_gray, size = 5) +
  geom_line(df_13, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_13, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_13, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-05-01"), year, "")), 
            hjust = -.5, vjust = 0.6, color = my_light_gray, size = 5) +
  geom_line(df_12, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_12, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_12, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-05-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_17, mapping = aes(x = date, y = self_h), color = another_blue, alpha = 0.5) +
  geom_point(df_17, mapping = aes(x = date, y = self_h, label = year), color = another_blue, size = 3, shape = 17) +
  geom_text(df_17, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-05-01"), year, "")), 
            hjust = -.5, vjust = 0.33, color = another_blue, size = 5) +
  theme_classic() +
  theme(text = element_text(size = 20)) +
  scale_x_date(expand = c(0,30)) +
  scale_y_continuous(limits = c(3900, 13000)) +
  ylab("") +
  xlab("")

ggsave(here("plots", "model_free_labs.png"), width = 8, height = 5, unit = "in")  

### FIGURE 15: DIFF-IN-DIFF PLOTS

tg <- tg %>%
  mutate(self_h_m = m40$self_h,
         self_h_w = w40$self_h,
         self_h_tb = tb$self_h,
         did_m = (self_h - lag(self_h)) - (self_h_m - lag(self_h_m)),
         did_w = (self_h - lag(self_h)) - (self_h_w - lag(self_h_w)),
         did_tb = (self_h - lag(self_h)) - (self_h_tb - lag(self_h_tb)),
         shcolor = ifelse(date < as.Date("2017-04-01"), 1,
                          ifelse(date < as.Date("2017-05-01"), 2, 3)))

tg_for_did <- tg[tg$date > as.Date("2006-01-01"),]
tg_for_did_pre <- tg_for_did[tg_for_did$date < as.Date("2017-04-01"),]

de_blue <- "#3E5C76"
mblue <- "#7EBDC2"
amaranth <- "#E83151"  

ggplot(tg_for_did) +
  geom_hline(yintercept = quantile(tg_for_did_pre$did_m, probs = .05), linetype = "dashed") +
  geom_hline(yintercept = quantile(tg_for_did_pre$did_m, probs = .95), linetype = "dashed") +
  geom_point(mapping = aes(x = date, y = did_m, color = factor(shcolor), shape = factor(shcolor)), size = 5) +
  scale_color_manual(values = c(de_blue, amaranth, mblue)) +
  scale_shape_manual(values = c(19, 17, 15)) +
  theme_classic() +
  theme(text = element_text(size = 75),
        legend.position = "none") +
  scale_x_date(breaks = c(seq.Date(from = as.Date("2006-10-01"), to = as.Date("2017-12-01"), by = "42 months")),
               date_labels = "%b %Y") +
  ylim(-2900,2900) +
  ylab("") +
  xlab("")

ggsave(here("plots", "did_m.png"), width = 9, height = 5, unit = "in")

ggplot(tg_for_did) +
  geom_hline(yintercept = quantile(tg_for_did_pre$did_w, probs = .05), linetype = "dashed") +
  geom_hline(yintercept = quantile(tg_for_did_pre$did_w, probs = .95), linetype = "dashed") +
  geom_point(mapping = aes(x = date, y = did_w, color = factor(shcolor), shape = factor(shcolor)), size = 5) +
  scale_color_manual(values = c(de_blue, amaranth, mblue)) +
  scale_shape_manual(values = c(19, 17, 15)) +
  theme_classic() +
  theme(text = element_text(size = 75),
        legend.position = "none") +
  scale_x_date(breaks = c(seq.Date(from = as.Date("2006-10-01"), to = as.Date("2017-12-01"), by = "42 months")),
               date_labels = "%b %Y") +
  ylim(-2900,2900) +
  ylab("") +
  xlab("")

ggsave(here("plots", "did_w.png"), width = 9, height = 5, unit = "in")

ggplot(tg_for_did) +
  geom_hline(yintercept = quantile(tg_for_did_pre$did_tb, probs = .05), linetype = "dashed") +
  geom_hline(yintercept = quantile(tg_for_did_pre$did_tb, probs = .95), linetype = "dashed") +
  geom_point(mapping = aes(x = date, y = did_tb, color = factor(shcolor), shape = factor(shcolor)), size = 5) +
  scale_color_manual(values = c(de_blue, amaranth, mblue)) +
  scale_shape_manual(values = c(19, 17, 15)) +
  theme_classic() +
  theme(text = element_text(size = 75),
        legend.position = "none") +
  scale_x_date(breaks = c(seq.Date(from = as.Date("2006-10-01"), to = as.Date("2017-12-01"), by = "42 months")),
               date_labels = "%b %Y") +
  ylim(-2900,2900) +
  ylab("") +
  xlab("")

ggsave(here("plots", "did_tb.png"), width = 9, height = 5, unit = "in")

#### APPENDIX ####

### APPENDIX A

## Complete lists of diagnosis codes are in diagnosis_codes.R.

### APPENDIX B

## B.1 P-VAL TABLES

split_pval_df <- get_pval_df(ts_est_conf_4,
                             T0 = length(ts_est_conf_1) - 1,
                             order = split_order,
                             seasonal = split_seasonal,
                             block_vec = c(1:4),
                             post_vec = c(1:3),
                             ts_start = c(2006,1),
                             include.mean = F)

safe_pval_df <- get_pval_df(ts_full_conf_4,
                            T0 = length(ts_full_conf_1) - 1,
                            order = split_order,
                            seasonal = split_seasonal,
                            block_vec = c(1:4),
                            post_vec = c(1:3),
                            ts_start = c(2006,1),
                            include.mean = F)

full_pval_df <- get_pval_df(ts_full_conf_4,
                            T0 = length(ts_full_conf_1) - 1,
                            order = full_order,
                            seasonal = full_seasonal,
                            block_vec = c(1:4),
                            post_vec = c(1:3),
                            ts_start = c(2006,1),
                            include.mean = F)

# Table B.1
print(xtable(full_pval_df, digits = 4), include.rownames = F)

# Table B.2
print(xtable(split_pval_df, digits = 4), include.rownames = F)

# Table B.3
print(xtable(safe_pval_df, digits = 4), include.rownames = F)

## B.2 TREATMENT EFFECTS W/ CONFIDENCE INTERVALS

split_CI_3 <- get_arima_CI(Y1 = ts_est_conf_1, 
                           T1 = 1,
                           T0 = length(ts_est_conf_1) - 1,
                           alpha = 0.05,
                           ci_grid = -1000:2500,
                           block_size = 3,
                           order = split_order,
                           seasonal = split_seasonal,
                           include.mean = F)

split_CI_2 <- get_arima_CI(Y1 = ts_est_conf_1, 
                           T1 = 1,
                           T0 = length(ts_est_conf_1) - 1,
                           alpha = 0.05,
                           ci_grid = 0:2165,
                           block_size = 2,
                           order = split_order,
                           seasonal = split_seasonal,
                           include.mean = F)

split_CI_1 <- get_arima_CI(Y1 = ts_est_conf_1, 
                           T1 = 1,
                           T0 = length(ts_est_conf_1) - 1,
                           alpha = 0.05,
                           ci_grid = 0:2165,
                           block_size = 1,
                           order = split_order,
                           seasonal = split_seasonal,
                           include.mean = F)

split_mod <- Arima(ts_est,
                   order = split_order,
                   seasonal = split_seasonal, method = "ML",
                   include.mean = F)

split_tau <- ts_est_conf_1[length(ts_est_conf_1)] - as.numeric(forecast(split_mod,h=1)$mean)

safe_CI_3 <- get_arima_CI(Y1 = ts_full_conf_1, 
                          T1 = 1,
                          T0 = length(ts_full_conf_1) - 1,
                          alpha = 0.05,
                          ci_grid = -100:2500,
                          block_size = 3,
                          order = split_order,
                          seasonal = split_seasonal,
                          include.mean = F)

safe_CI_2 <- get_arima_CI(Y1 = ts_full_conf_1, 
                          T1 = 1,
                          T0 = length(ts_full_conf_1) - 1,
                          alpha = 0.05,
                          ci_grid = -100:2500,
                          block_size = 2,
                          order = split_order,
                          seasonal = split_seasonal,
                          include.mean = F)

safe_CI_1 <- get_arima_CI(Y1 = ts_full_conf_1, 
                          T1 = 1,
                          T0 = length(ts_full_conf_1) - 1,
                          alpha = 0.05,
                          ci_grid = -100:2500,
                          block_size = 1,
                          order = split_order,
                          seasonal = split_seasonal,
                          include.mean = F)

safe_mod <- Arima(pre_ts,
                  order = split_order,
                  seasonal = split_seasonal, method = "ML",
                  include.mean = F)

safe_tau <- ts_est_conf_1[length(ts_est_conf_1)] - as.numeric(forecast(safe_mod,h=1)$mean)

full_CI_3 <- get_arima_CI(Y1 = ts_full_conf_1, 
                          T1 = 1,
                          T0 = length(ts_full_conf_1) - 1,
                          alpha = 0.05,
                          ci_grid = 0:2700,
                          block_size = 3,
                          order = full_order,
                          seasonal = full_seasonal,
                          include.mean = F)

full_CI_2 <- get_arima_CI(Y1 = ts_full_conf_1, 
                          T1 = 1,
                          T0 = length(ts_full_conf_1) - 1,
                          alpha = 0.05,
                          ci_grid = 0:2700,
                          block_size = 2,
                          order = full_order,
                          seasonal = full_seasonal,
                          include.mean = F)

full_CI_1 <- get_arima_CI(Y1 = ts_full_conf_1, 
                          T1 = 1,
                          T0 = length(ts_full_conf_1) - 1,
                          alpha = 0.05,
                          ci_grid = 0:2700,
                          block_size = 1,
                          order = full_order,
                          seasonal = full_seasonal,
                          include.mean = F)

full_mod <- Arima(pre_ts,
                  order = full_order,
                  seasonal = full_seasonal, method = "ML",
                  include.mean = F)

full_tau <- ts_est_conf_1[length(ts_est_conf_1)] - as.numeric(forecast(full_mod,h=1)$mean)

block_size <- rep(c(1,2,3),3)
est_method <- c(rep("Split",3), rep("SAFE",3), rep("Full",3))
tau <- c(rep(split_tau,3), rep(safe_tau,3), rep(full_tau,3))
upper <- c(split_CI_1$ub, split_CI_2$ub, split_CI_3$ub,
           safe_CI_1$ub,safe_CI_2$ub,safe_CI_3$ub,
           full_CI_1$ub,full_CI_2$ub,full_CI_3$ub)
lower <- c(split_CI_1$lb, split_CI_2$lb, split_CI_3$lb,
           safe_CI_1$lb,safe_CI_2$lb,safe_CI_3$lb,
           full_CI_1$lb,full_CI_2$lb,full_CI_3$lb)

tau_df <- data.frame(block_size, est_method, tau, upper, lower)

ggplot(tau_df) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_point(mapping = aes(x = factor(block_size), y = tau), size = 3) +
  geom_errorbar(mapping = aes(x = block_size, y = tau, ymin = lower, ymax = upper), width = 0, size = .75) +
  facet_wrap(vars(est_method)) +
  theme_bw() +
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  #scale_x_date(expand = c(0,40),
  #date_labels = "%b") +
  #scale_y_continuous(limits = c(3500, 11700)) +
  ylab("") +
  xlab("")

ggsave(here("plots", "tau_plot.png"), width = 8, height = 5, units = "in")

## B.3 PLACEBO TEST RESULTS

# Again, these can be found in repeat_placebo.R since they
# take a long time to run.

## B.4 RESIDUAL PLOTS FOR ALTERNATIVE MODEL
## SPECIFICATIONS

# Figre B.8: Model selected on full time series

complete_mod_s <- auto.arima(full_ts)

abs_res_s <- abs(as.numeric(complete_mod_s$residuals))[14:length(complete_mod_s$residuals)]

res_s <- as.numeric(complete_mod_s$residuals)[14:length(complete_mod_s$residuals)]

dates <- seq.Date(from = as.Date("2007-02-01"),
                  to = as.Date("2017-12-01"),
                  by = "1 month")

plot_month_df <- data.frame(abs_res_s, res_s, dates) %>%
  mutate(mon = format(dates, "%b"),
         year = format(dates, "%Y"),
         shcolor = ifelse(dates < as.Date("2017-04-01"), 1,
                          ifelse(dates < as.Date("2017-06-01"), 2, 3)))

plot_month_0916 <- plot_month_df %>%
  filter(year != "2017")

plot_month_17 <- plot_month_df %>%
  filter(year == "2017") %>%
  mutate(treat = ifelse(dates < as.Date("2017-04-01"), 0, 1))

dgray <- "#7e8082"
lgray <- "#b5b9bc"

ggplot() +
  geom_hline(yintercept = 0, linetype = "dotted") +
  geom_point(plot_month_df, mapping = aes(x = dates, y = res_s, shape = factor(shcolor), color = factor(shcolor)), size = 4) +
  scale_shape_manual(values = c(19, 17, 15)) +
  scale_color_manual(values = c(dgray, my_red, lgray)) +
  theme_classic() +
  theme(legend.title = element_blank(),
        legend.position = "none",
        text = element_text(size = 20)) +
  ylim(-1400, 1400) +
  labs(x = "",
       y = "")

ggsave(here("plots", "res_plot_s.png"), width = 8, height = 5, unit = "in")

# Figure B.9: Split model specification run on full time series.


simple_mod <- Arima(full_ts, order = split_order, seasonal = split_seasonal)

abs_res <- abs(as.numeric(simple_mod$residuals))[14:length(simple_mod$residuals)]

res <- as.numeric(simple_mod$residuals)[14:length(simple_mod$residuals)]

dates <- seq.Date(from = as.Date("2007-02-01"),
                  to = as.Date("2017-12-01"),
                  by = "1 month")

plot_month_df <- data.frame(abs_res, res, dates) %>%
  mutate(mon = format(dates, "%b"),
         year = format(dates, "%Y"),
         shcolor = ifelse(dates < as.Date("2017-04-01"), 1,
                          ifelse(dates < as.Date("2017-06-01"), 2, 3)))

plot_month_0916 <- plot_month_df %>%
  filter(year != "2017")

plot_month_17 <- plot_month_df %>%
  filter(year == "2017") %>%
  mutate(treat = ifelse(dates < as.Date("2017-04-01"), 0, 1))

ggplot() +
  geom_hline(yintercept = 0, linetype = "dotted") +
  geom_point(plot_month_df, mapping = aes(x = dates, y = res, shape = factor(shcolor), color = factor(shcolor)), size = 4) +
  scale_shape_manual(values = c(19, 17, 15)) +
  scale_color_manual(values = c(dgray, my_red, lgray)) +
  theme_classic() +
  theme(legend.title = element_blank(),
        legend.position = "none",
        text = element_text(size = 20)) +
  ylim(-1400, 1400) +
  labs(x = "",
       y = "")

ggsave(here("plots", "res_plot_split.png"), width = 8, height = 5, unit = "in")

# Figure B.10: Arbitrarily selected more complex model

complex_mod <- Arima(full_ts, order = c(3,1,1), seasonal = c(1,1,0))

abs_res <- abs(as.numeric(complex_mod$residuals))[14:length(complex_mod$residuals)]

res <- as.numeric(complex_mod$residuals)[14:length(complex_mod$residuals)]

dates <- seq.Date(from = as.Date("2007-02-01"),
                  to = as.Date("2017-12-01"),
                  by = "1 month")

plot_month_df <- data.frame(abs_res, res, dates) %>%
  mutate(mon = format(dates, "%b"),
         year = format(dates, "%Y"),
         shcolor = ifelse(dates < as.Date("2017-04-01"), 1,
                          ifelse(dates < as.Date("2017-06-01"), 2, 3)))

plot_month_0916 <- plot_month_df %>%
  filter(year != "2017")

plot_month_17 <- plot_month_df %>%
  filter(year == "2017") %>%
  mutate(treat = ifelse(dates < as.Date("2017-04-01"), 0, 1))

ggplot() +
  geom_hline(yintercept = 0, linetype = "dotted") +
  geom_point(plot_month_df, mapping = aes(x = dates, y = res, shape = factor(shcolor), color = factor(shcolor)), size = 4) +
  scale_shape_manual(values = c(19, 17, 15)) +
  scale_color_manual(values = c(dgray, my_red, lgray)) +
  theme_classic() +
  theme(legend.title = element_blank(),
        legend.position = "none",
        text = element_text(size = 20)) +
  ylim(-1400, 1400) +
  labs(x = "",
       y = "")

ggsave(here("plots", "res_plot_c.png"), width = 8, height = 5, unit = "in")

# Figure B.11: Another arbitrarily selected more complex model

complex_mod <- Arima(full_ts, order = c(4,1,2), seasonal = c(1,1,0))

abs_res <- abs(as.numeric(complex_mod$residuals))[14:length(complex_mod$residuals)]

res <- as.numeric(complex_mod$residuals)[14:length(complex_mod$residuals)]

dates <- seq.Date(from = as.Date("2007-02-01"),
                  to = as.Date("2017-12-01"),
                  by = "1 month")

plot_month_df <- data.frame(abs_res, res, dates) %>%
  mutate(mon = format(dates, "%b"),
         year = format(dates, "%Y"),
         shcolor = ifelse(dates < as.Date("2017-04-01"), 1,
                          ifelse(dates < as.Date("2017-06-01"), 2, 3)))

plot_month_0916 <- plot_month_df %>%
  filter(year != "2017")

plot_month_17 <- plot_month_df %>%
  filter(year == "2017") %>%
  mutate(treat = ifelse(dates < as.Date("2017-04-01"), 0, 1))

ggplot() +
  geom_hline(yintercept = 0, linetype = "dotted") +
  geom_point(plot_month_df, mapping = aes(x = dates, y = res, shape = factor(shcolor), color = factor(shcolor)), size = 4) +
  scale_shape_manual(values = c(19, 17, 15)) +
  scale_color_manual(values = c(dgray, my_red, lgray)) +
  theme_classic() +
  theme(legend.title = element_blank(),
        legend.position = "none",
        text = element_text(size = 20)) +
  ylim(-1400, 1400) +
  labs(x = "",
       y = "")

ggsave(here("plots", "res_plot_c2.png"), width = 8, height = 5, unit = "in")

## B.5 ARIMA TABLES

# I made the ARIMA tables myself in LaTeX since xtable / stargazer
# can't take ARIMA models.

ts_train <- ts(ts_full_conf_1[1:74], start = c(2006, 1), freq = 12)

# Table B.4 Split specification on training set
Arima(ts_train, order = split_order, seasonal = split_seasonal)

# Table B.5 Split specification on estimation set
Arima(ts_est, order = split_order, seasonal = split_seasonal)

# Table B.6 Split specification on all pre-treatment periods (SAFE)
Arima(pre_ts, order = split_order, seasonal = split_seasonal)

# Table B.7 Full specification on all pre-treatment periods
Arima(pre_ts, order = full_order, seasonal = full_seasonal)

## B.6 MODEL-FREE PLOTS

# Figure B.12: Self-harm visits for the full time series,
# plotted by year.

for_names <- c("06", "07", "08", "09", "10", "11", 
               "12", "13", "14", "15", "16", "17")

# These are not the actual dates, just dates to make plotting in ggplot
# easier, since we're plotting a different line for each year
ggplot_dates <- seq.Date(from = as.Date("2017-01-01"), to = as.Date("2017-12-01"), by = "1 month")

for (i in 1:length(for_names)) {
  
  df_temp <- tg %>%
    filter(year == as.numeric(paste0("20", for_names[i]))) %>%
    select(self_h, date) %>%
    mutate(date = ggplot_dates,
           year = paste0("20", for_names[i]))
  
  df_name <- paste0("df_", for_names[i], "_full")
  eval(call("<-", as.name(df_name), df_temp))
  
}

my_light_gray <- "#a0a6ac"
another_blue <- "#3080d0"

# Using wide y-lims to make room for labels in latex

ggplot() +
  geom_vline(df_17_full, mapping = aes(x = date, xintercept = as.Date("2017-02-15")), linetype = "dashed") +
  geom_vline(df_17_full, mapping = aes(x = date, xintercept = as.Date("2017-03-15")), linetype = "dashed") +
  geom_line(df_06_full, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_06_full, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_06_full, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-12-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_07_full, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_07_full, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_07_full, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-12-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_08_full, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_08_full, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_08_full, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-12-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_09_full, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_09_full, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_09_full, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-12-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_10_full, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_10_full, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_10_full, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-12-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_11_full, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_11_full, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_11_full, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-12-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_12_full, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_12_full, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_12_full, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-12-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_13_full, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_13_full, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_13_full, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-12-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_14_full, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_14_full, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_14_full, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-12-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_15_full, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_15_full, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_15_full, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-12-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_16_full, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_16_full, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_16_full, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-12-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_17_full, mapping = aes(x = date, y = self_h), color = another_blue, alpha = 0.5) +
  geom_point(df_17_full, mapping = aes(x = date, y = self_h, label = year), color = another_blue, size = 3, shape = 17) +
  geom_text(df_17_full, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-12-01"), year, "")), 
            hjust = -.5, vjust = 0.33, color = another_blue, size = 5) +
  theme_classic() +
  theme(text = element_text(size = 20)) +
  scale_x_date(expand = c(0,40),
               date_labels = "%b",
               breaks = c(as.Date("2017-01-01"),
                          as.Date("2017-04-01"),
                          as.Date("2017-07-01"),
                          as.Date("2017-10-01"))) +
  scale_y_continuous(limits = c(3500, 11700)) +
  ylab("") +
  xlab("")

ggsave(here("plots", "model_free_full.png"), width = 8, height = 5, unit = "in")  

# Figure B.13: Self-harm visits across all Febs and Mars

ggplot_dates <- c(as.Date("2017-02-01"), as.Date("2017-03-01"))

start_dates <- seq.Date(from = as.Date("2006-02-01"), to = as.Date("2017-02-01"), by = "1 year")
end_dates <- seq.Date(from = as.Date("2006-03-01"), to = as.Date("2017-03-01"), by = "1 year")

for (i in 1:length(for_names)) {
  
  df_temp <- tg %>%
    filter(date >= start_dates[i] & date <= end_dates[i]) %>%
    select(self_h, date) %>%
    mutate(date = ggplot_dates,
           year = paste0("20", for_names[i]))
  
  df_name <- paste0("df_", for_names[i], "_feb")
  eval(call("<-", as.name(df_name), df_temp))
  
}

ggplot() +
  geom_line(df_06_feb, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_06_feb, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_06_feb, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-03-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_07_feb, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_07_feb, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_07_feb, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-03-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_08_feb, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_08_feb, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_08_feb, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-03-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_09_feb, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_09_feb, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_09_feb, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-03-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_10_feb, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_10_feb, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_10_feb, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-03-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_11_feb, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_11_feb, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_11_feb, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-03-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_12_feb, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_12_feb, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_12_feb, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-03-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_13_feb, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_13_feb, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_13_feb, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-03-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_14_feb, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_14_feb, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_14_feb, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-03-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_15_feb, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_15_feb, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_15_feb, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-03-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_16_feb, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_16_feb, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_16_feb, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-03-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_17_feb, mapping = aes(x = date, y = self_h), color = another_blue, alpha = 0.5) +
  geom_point(df_17_feb, mapping = aes(x = date, y = self_h, label = year), color = another_blue, size = 3, shape = 17) +
  geom_text(df_17_feb, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-03-01"), year, "")), 
            hjust = -.5, vjust = 0.33, color = another_blue, size = 5) +
  theme_classic() +
  theme(text = element_text(size = 20)) +
  scale_x_date(expand = c(0,10),
               date_labels = "%b",
               limits = c(as.Date("2017-02-01"), as.Date("2017-03-01")),
               breaks = c(as.Date("2017-02-01"), as.Date("2017-03-01"))) +
  scale_y_continuous(limits = c(4000, 10000)) +
  ylab("") +
  xlab("")

ggsave(here("plots", "feb.png"), width = 5, height = 5, units = "in")

# Figure B.14: Self-harm visits across all Mars and Aprs

ggplot_dates <- c(as.Date("2017-03-01"), as.Date("2017-04-01"))

start_dates <- seq.Date(from = as.Date("2006-03-01"), to = as.Date("2017-03-01"), by = "1 year")
end_dates <- seq.Date(from = as.Date("2006-04-01"), to = as.Date("2017-04-01"), by = "1 year")

for (i in 1:length(for_names)) {
  
  df_temp <- tg %>%
    filter(date >= start_dates[i] & date <= end_dates[i]) %>%
    select(self_h, date) %>%
    mutate(date = ggplot_dates,
           year = paste0("20", for_names[i]))
  
  df_name <- paste0("df_", for_names[i], "_mar")
  eval(call("<-", as.name(df_name), df_temp))
  
}

ggplot() +
  geom_line(df_06_mar, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_06_mar, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_06_mar, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-04-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_07_mar, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_07_mar, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_07_mar, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-04-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_08_mar, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_08_mar, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_08_mar, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-04-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_09_mar, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_09_mar, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_09_mar, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-04-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_10_mar, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_10_mar, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_10_mar, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-04-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_11_mar, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_11_mar, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_11_mar, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-04-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_12_mar, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_12_mar, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_12_mar, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-04-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_13_mar, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_13_mar, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_13_mar, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-04-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_14_mar, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_14_mar, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_14_mar, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-04-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_15_mar, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_15_mar, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_15_mar, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-04-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_16_mar, mapping = aes(x = date, y = self_h), color = my_light_gray, alpha = 0.5) +
  geom_point(df_16_mar, mapping = aes(x = date, y = self_h, label = year), color = my_light_gray, size = 3, shape = 15) +
  geom_text(df_16_mar, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-04-01"), year, "")), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 5) +
  geom_line(df_17_mar, mapping = aes(x = date, y = self_h), color = another_blue, alpha = 0.5) +
  geom_point(df_17_mar, mapping = aes(x = date, y = self_h, label = year), color = another_blue, size = 3, shape = 17) +
  geom_text(df_17_mar, mapping = aes(x = date, y = self_h, label = ifelse(date == as.Date("2017-04-01"), year, "")), 
            hjust = -.5, vjust = 0.33, color = another_blue, size = 5) +
  theme_classic() +
  theme(text = element_text(size = 20)) +
  scale_x_date(expand = c(0,10),
               date_labels = "%b",
               limits = c(as.Date("2017-03-01"), as.Date("2017-04-01")),
               breaks = c(as.Date("2017-03-01"), as.Date("2017-04-01"))) +
  scale_y_continuous(limits = c(4000, 11000)) +
  ylab("") +
  xlab("")

ggsave(here("plots", "mar.png"), width = 5, height = 5, units = "in")

# Figure B.15: First-differenced self-harm visits by month

df_fd <- na.omit(data.frame(date = tg$date, selfh = tg$self_h_fd, month = tg$amonth)) %>%
  mutate(mon = format(date, "%b"),
         year = format(date, "%Y"),
         shcolor = ifelse(date < as.Date("2017-04-01"), 1,
                          ifelse(date < as.Date("2017-06-01"), 2, 3)))

df_fd_0916 <- df_fd %>%
  filter(year != "2017")

df_fd_17 <- df_fd %>%
  filter(year == "2017") %>%
  mutate(treat = ifelse(date < as.Date("2017-04-01"), 0, 1))

ggplot() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_point(df_fd_0916, mapping = aes(x = mon, y = selfh), shape = 16, size = 3.3, 
             color = my_light_gray, alpha = 0.6) +
  geom_text(df_fd_0916, mapping = aes(x = mon, y = selfh, label = year), 
            hjust = -.5, vjust = 0.45, color = my_light_gray, size = 3, alpha = 0.6) +
  geom_point(df_fd_17, mapping = aes(x = mon, y = selfh, shape = factor(treat), color = factor(treat), size = factor(treat))) +
  scale_shape_manual(values = c(16, 17)) +
  scale_color_manual(values = c(my_red, my_green)) +
  scale_size_manual(values = c(3.3,3)) +
  geom_text(df_fd_17, mapping = aes(x = mon, y = selfh, label = year, color = factor(treat)), 
            hjust = -.5, vjust = 0.45, size = 3) +
  #scale_color_manual(values = c(my_red, my_green)) +
  theme_classic() +
  theme(legend.title = element_blank(),
        legend.position = "none",
        text = element_text(size = 20)) +
  scale_x_discrete(limits = c("Jan", "Feb", "Mar", "Apr", "May",
                              "Jun", "Jul", "Aug", "Sep", "Oct",
                              "Nov", "Dec"),
                   expand = c(0,1)) + 
  scale_y_continuous(limits = c(-3500,3500), expand = c(0,40),
                     breaks = c(-3000,-1500,0,1500,3000)) +
  labs(x = "",
       y = "")

ggsave(here("plots", "fd.png"), width = 8, height = 5, unit = "in")

# Figure B.16: Proportion of self-harm visits for cutting

dgray <- "#7e8082"
lgray <- "#b5b9bc"

ggplot(tg) +
  geom_hline(yintercept = prop_lower, linetype = "dashed") +
  geom_hline(yintercept = prop_upper, linetype = "dashed") +
  geom_point(mapping = aes(x = date, y = cut_prop, color = factor(shcolor), shape = factor(shcolor)), size = 4) +
  scale_shape_manual(values = c(19, 17, 15)) +
  scale_color_manual(values = c(dgray, my_red, lgray)) +
  theme_classic() +
  theme(text = element_text(size = 20),
        legend.position = "none") +
  scale_x_date(breaks = c(as.Date("2008-01-01"), as.Date("2012-01-01"), as.Date("2016-01-01")),
               date_labels = "%b %Y") +
  ylab("") +
  xlab("")

ggsave(here("plots", "cut_prop_raw.png"), width = 8, height = 5, unit = "in")

## B.7 ITS PLOTS WITH ALTERNATIVE TIME SERIES

# Figure B.17 Girls 10-17
tg17 <- readRDS(here("data", "tg17_selfh_all_full.rds"))
tg17_ts <- create_ts(tg17)
tg17_ts_pre <- tg17_ts$pre_ts
tg17_ts_post <- tg17_ts$ts_full_conf_1
ords <- give_me_order(tg17_ts_pre)

tg17_mod <- Arima(tg17_ts_pre, order = ords$order, seasonal = ords$seasonal, include.mean = F)

tg17_PI <- get_arima_PI(tg17_ts_post, 
                        T1 = 1, 
                        T0 = length(tg17_ts_pre),
                        alpha = 0.05, 
                        pi_grid = 5000:8000, 
                        block_size = 1,
                        order = ords$order, 
                        seasonal = ords$seasonal, 
                        include.mean = F)

tg17_upper <- tg17_PI$ub
tg17_lower <- tg17_PI$lb

tg17_dfs <- get_plot_dfs(tg17_ts_post, tg17_mod, tg17_upper, tg17_lower)

get_control_plot(pre_df = tg17_dfs$pre_df,
                 post_df = tg17_dfs$post_df,
                 name = "tg17",
                 y_min = 5000,
                 y_max = 9000)

# Figure B.18 Poisoning and cutting only
tg_poiscut <- readRDS(here("data", "tg_pois_cut_all_full.rds"))
tg_poiscut_ts <- create_ts(tg_poiscut)
tg_poiscut_ts_pre <- tg_poiscut_ts$pre_ts
tg_poiscut_ts_post <- tg_poiscut_ts$ts_full_conf_1
ords <- give_me_order(tg_poiscut_ts_pre)

tg_poiscut_mod <- Arima(tg_poiscut_ts_pre, order = ords$order, seasonal = ords$seasonal, include.mean = F)

tg_poiscut_PI <- get_arima_PI(tg_poiscut_ts_post, 
                              T1 = 1, 
                              T0 = length(tg_poiscut_ts_pre),
                              alpha = 0.05, 
                              pi_grid = 7000:10000, 
                              block_size = 1,
                              order = ords$order, 
                              seasonal = ords$seasonal, 
                              include.mean = F)

tg_poiscut_upper <- tg_poiscut_PI$ub
tg_poiscut_lower <- tg_poiscut_PI$lb

tg_poiscut_dfs <- get_plot_dfs(tg_poiscut_ts_post, tg_poiscut_mod, tg_poiscut_upper, tg_poiscut_lower)

get_control_plot(pre_df = tg_poiscut_dfs$pre_df,
                 post_df = tg_poiscut_dfs$post_df,
                 name = "tg_poiscut",
                 y_min = 6000,
                 y_max = 10000)

# Figure B.19 Series starting at Jan 2013
tg2013 <- readRDS(here("data", "tg_self_harm.rds"))
tg2013_ts <- create_ts(tg2013)
tg2013_ts_pre <- tg2013_ts$pre_ts %>%
  window(start = c(2013,1))
tg2013_ts_post <- tg2013_ts$ts_full_conf_1 %>%
  window(start = c(2013,1))
ords <- give_me_order(tg2013_ts_pre)

tg2013_mod <- Arima(tg2013_ts_pre, order = ords$order, seasonal = ords$seasonal, include.mean = F)

tg2013_PI <- get_arima_PI(tg2013_ts_post, 
                          T1 = 1, 
                          T0 = length(tg2013_ts_pre),
                          alpha = 0.05, 
                          pi_grid = 7000:11000, 
                          block_size = 1,
                          order = ords$order, 
                          seasonal = ords$seasonal, 
                          include.mean = F)

tg2013_upper <- tg2013_PI$ub
tg2013_lower <- tg2013_PI$lb

tg2013_dfs <- get_plot_dfs(tg2013_ts_post, tg2013_mod, tg2013_upper, tg2013_lower)

get_control_plot(pre_df = tg2013_dfs$pre_df,
                 post_df = tg2013_dfs$post_df,
                 name = "tg2013",
                 y_min = 6500,
                 y_max = 10500)

# Figure B.20 Series starting at Jan 2014
tg2014 <- readRDS(here("data", "tg_self_harm.rds"))
tg2014_ts <- create_ts(tg2014)
tg2014_ts_pre <- tg2014_ts$pre_ts %>%
  window(start = c(2014,1))
tg2014_ts_post <- tg2014_ts$ts_full_conf_1 %>%
  window(start = c(2014,1))
ords <- give_me_order(tg2014_ts_pre)

tg2014_mod <- Arima(tg2014_ts_pre, order = ords$order, seasonal = ords$seasonal, include.mean = F)

tg2014_PI <- get_arima_PI(tg2014_ts_post, 
                          T1 = 1, 
                          T0 = length(tg2014_ts_pre),
                          alpha = 0.05, 
                          pi_grid = 7000:11000, 
                          block_size = 1,
                          order = ords$order, 
                          seasonal = ords$seasonal, 
                          include.mean = F)

tg2014_upper <- tg2014_PI$ub
tg2014_lower <- tg2014_PI$lb

tg2014_dfs <- get_plot_dfs(tg2014_ts_post, tg2014_mod, tg2014_upper, tg2014_lower)

get_control_plot(pre_df = tg2014_dfs$pre_df,
                 post_df = tg2014_dfs$post_df,
                 name = "tg2014",
                 y_min = 6500,
                 y_max = 10500)

# Figure B.21 Unweighted counts of self-harm visits
unweighted <- readRDS(here("data", "unweighted", "tg_selfh_unweighted.rds"))

unw_ts <- create_ts(unweighted)
unw_ts_pre <- unw_ts$pre_ts
unw_ts_post <- unw_ts$ts_full_conf_1
ords <- give_me_order(unw_ts_pre)

unw_mod <- Arima(unw_ts_pre, order = ords$order, seasonal = ords$seasonal, include.mean = F)

unw_PI <- get_arima_PI(unw_ts_post, 
                       T1 = 1, 
                       T0 = length(unw_ts_pre),
                       alpha = 0.05, 
                       pi_grid = 1700:2500, 
                       block_size = 1,
                       order = ords$order, 
                       seasonal = ords$seasonal, 
                       include.mean = F)

unw_upper <- unw_PI$ub
unw_lower <- unw_PI$lb

unw_dfs <- get_plot_dfs(unw_ts_post, unw_mod, unw_upper, unw_lower)

get_control_plot(pre_df = unw_dfs$pre_df,
                 post_df = unw_dfs$post_df,
                 name = "unw",
                 y_min = 1250,
                 y_max = 2500)

# Figure B.22 Teen boys with alternative specification
ords <- give_me_order(tb_ts_pre)

tb_mod <- Arima(tb_ts_pre, order = ords$order, seasonal = ords$seasonal, include.mean = F)

tb_PI <- get_arima_PI(tb_ts_post, 
                      T1 = 1, 
                      T0 = length(tb_ts_pre),
                      alpha = 0.05, 
                      pi_grid = 2500:3800, 
                      block_size = 1,
                      order = ords$order, 
                      seasonal = ords$seasonal, 
                      include.mean = F)

tb_upper <- tb_PI$ub
tb_lower <- tb_PI$lb

tb_dfs <- get_plot_dfs(tb_ts_post, tb_mod, tb_upper, tb_lower)

get_control_plot(pre_df = tb_dfs$pre_df,
                 post_df = tb_dfs$post_df,
                 name = "tb_alt",
                 y_min = 1000,
                 y_max = 5000)

# Figure B.23 Teen girls "suicide attempt" code


attempt <- readRDS(here("data", "tg_attempt.rds"))

date_vec <- seq.Date(from = as.Date("2017-01-01"), to = as.Date("2017-05-01"), by = "1 month")

attempt_16 <- attempt %>%
  filter(date < as.Date("2016-06-01")) %>%
  mutate(date = date_vec)

attempt_17 <- attempt %>%
  filter(year == 2017,
         date < as.Date("2017-06-01"))

ggplot() +
  geom_vline(mapping = aes(xintercept = as.Date("2017-02-15")), linetype = "dashed", size =.3) +
  geom_vline(mapping = aes(xintercept = as.Date("2017-03-15")), linetype = "dashed", size = .3) +
  geom_line(data = attempt_16, mapping = aes(x = date, y=self_h), color = my_gray, alpha = 0.6) +
  geom_point(data = attempt_16, mapping = aes(x = date, y=self_h), size = 3, shape = 19, color = my_gray) +
  geom_text(data = attempt_16, mapping = aes(x = date, y = self_h, 
                                             label = ifelse(date == as.Date("2017-05-01"), year, "")),
            hjust = -.5, vjust = 0.45, color = my_gray) +
  geom_line(data = attempt_17, mapping = aes(x = date, y=self_h), alpha = 0.6, color = unintentRed) +
  geom_point(data = attempt_17, mapping = aes(x = date, y=self_h), size = 3, shape = 15, color = unintentRed) +
  geom_text(data = attempt_17, mapping = aes(x = date, y = self_h, 
                                             label = ifelse(date == as.Date("2017-05-01"), year, "")),
            hjust = -.5, vjust = 0.45, color = unintentRed) +
  theme_classic() +
  theme(text = element_text(size = 20),
        legend.position = "none") +
  scale_x_date(
    #date_labels = "%b %Y",
    #limits = c(as.Date("2016-01-01"), as.Date("2017-04-01")),
    expand = c(0,11)) +
  #ylim(-2900,2900) +
  ylab("") +
  xlab("")

ggsave(here("plots", "attempt.png"), width = 8, height = 5, units = "in")

### APPENDIX C ###

## Code is in sims.R.

### APPENDIX D ###

## Code is in sims.R.

### APPENDIX E ###

## PEDAGOGICAL CONFORMAL PLOTS

# Figure E.2 illustrating conformal p-values

y_star <- 11000

ts_aug <- ts(c(ts_est, y_star), 
             start = start(ts_est),  
             frequency = frequency(ts_est))

#Fitting model to augmented ts
mod_aug <- Arima(ts_aug, 
                 order = split_order,
                 seasonal = split_seasonal)

#Extracting fitted values
fit_aug <- fitted(mod_aug)

res_aug <- residuals(mod_aug)

#Creating df for ggplot2
conf_plot_df <- data.frame(fit = fit_aug,
                           res = res_aug,
                           obs = ts_aug, 
                           date = as.Date(ts_aug))

conf_plot_df$aug <- ifelse(conf_plot_df$date == as.Date("2017-04-01"), 1, 0)
conf_plot_df$pre_obs <- conf_plot_df$obs

conf_plot_df <- conf_plot_df[14:75,]
conf_plot_df$pre_obs[62] <- NA_integer_

red_seg_df <- conf_plot_df[abs(conf_plot_df$res) >= abs(conf_plot_df$res[62]),]
blue_seg_df <- conf_plot_df[abs(conf_plot_df$res) < abs(conf_plot_df$res[62]),]

post_df <- conf_plot_df[62,]

my_red <- "#d72631"
my_blue <- "#1786bd"
my_light_blue <- "#8ec6e1"

min(conf_plot_df$fit)
min(conf_plot_df$obs)

y_lims <- c(3800, 11000)

#Plot with just pre-treatment series in gray
ggplot() +
  geom_point(conf_plot_df, 
             mapping = aes(x = date, y = pre_obs), 
             size = 2.5, color = my_gray) +
  theme_classic() +
  theme(text = element_text(size = 20)) +
  scale_x_date(limits = c(as.Date("2012-03-01"), as.Date("2017-05-01")), expand = c(0,50)) +
  scale_y_continuous(limits = y_lims) +
  ylab("") +
  xlab("")

ggsave(here("plots", "confplot1.png"), width = 8, height = 5, unit = "in")

ggplot() +
  geom_point(conf_plot_df, 
             mapping = aes(x = date, y = pre_obs), 
             size = 2.5, color = my_gray) +
  geom_point(post_df, 
             mapping = aes(x = date, y = obs), 
             size = 2.5, color = my_red) +
  theme_classic() +
  theme(text = element_text(size = 20)) +
  scale_x_date(limits = c(as.Date("2012-03-01"), as.Date("2017-05-01")), expand = c(0,50)) +
  scale_y_continuous(limits = y_lims) +
  ylab("") +
  xlab("")

ggsave(here("plots", "confplot2.png"), width = 8, height = 5, unit = "in")

ggplot() +
  geom_segment(conf_plot_df, 
               mapping = aes(x = date, xend = date, y = pre_obs, yend = fit), 
               color = my_light_blue) +
  geom_segment(post_df, 
               mapping = aes(x = date, xend = date, y = obs, yend = fit), 
               color = my_light_blue) +
  geom_line(conf_plot_df, 
            mapping = aes(x = date, y = fit)) +
  geom_point(conf_plot_df, 
             mapping = aes(x = date, y = pre_obs), 
             size = 2.5, color =  my_blue) +
  geom_point(post_df, 
             mapping = aes(x = date, y = obs), 
             size = 2.5, color = my_blue) +
  theme_classic() +
  theme(text = element_text(size = 20)) +
  scale_x_date(limits = c(as.Date("2012-03-01"), as.Date("2017-05-01")), expand = c(0,50)) +
  scale_y_continuous(limits = y_lims) +
  ylab("") +
  xlab("")

ggsave(here("plots", "confplot3.png"), width = 8, height = 5, unit = "in")

ggplot() +
  geom_segment(conf_plot_df, 
               mapping = aes(x = date, xend = date, y = pre_obs, yend = fit), 
               color = my_light_blue) +
  geom_segment(post_df, 
               mapping = aes(x = date, xend = date, y = obs, yend = fit), 
               color = my_light_blue) +
  geom_line(conf_plot_df, 
            mapping = aes(x = date, y = fit)) +
  geom_point(conf_plot_df, 
             mapping = aes(x = date, y = pre_obs), 
             size = 2.5, color =  my_blue) +
  geom_point(post_df, 
             mapping = aes(x = date, y = obs), 
             size = 2.5, color = my_red) +
  theme_classic() +
  theme(text = element_text(size = 20)) +
  scale_x_date(limits = c(as.Date("2012-03-01"), as.Date("2017-05-01")), expand = c(0,50)) +
  scale_y_continuous(limits = y_lims) +
  ylab("") +
  xlab("")

ggsave(here("plots", "confplot4.png"), width = 8, height = 5, unit = "in")

# Figure E.3 Plots illustrating test inversion

lapply(c(11000, 10000, 9750, 9500), make_pval_plot)

### APPENDIX F ###

## Code is in sims.R.





